package edison.pokemon_try;

import android.content.DialogInterface;
import android.content.Intent;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.os.Bundle;
import android.provider.ContactsContract;
import android.support.annotation.Nullable;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by MSI on 2016/12/15.
 */
public class main_activity extends AppCompatActivity {
    private pokemonDB pokeDB;
    private pokemonlist pokeList;
    private ArrayList<HashMap<String, String>> listmap ;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.main_layout);

        pokeDB = new pokemonDB(this);

        final AlertDialog.Builder log = new AlertDialog.Builder(main_activity.this).setTitle("功能仍在开发中").setMessage("如有建议，欢迎来到我们的论坛进行讨论：\nhttp://bbs.edison-kun.com/");

        final Button button1 = (Button) findViewById(R.id.button1);
        final Button button2 = (Button) findViewById(R.id.button2);
        final Button button3 = (Button) findViewById(R.id.button3);
        final Button buttonDB = (Button) findViewById(R.id.buttonDB);

        if (buttonDB.getHint().equals("已更新数据")) {
            buttonDB.setVisibility(View.GONE);
        }

        log.setPositiveButton("确定", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialogInterface, int i) {
                Toast.makeText(main_activity.this, "谢谢您的支持！", Toast.LENGTH_SHORT).show();
            }
        });

        button1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (buttonDB.getHint().equals("已更新数据")) {
                    Intent intent = new Intent(main_activity.this, pokelist_activity.class);
                    startActivity(intent);
                } else {
                    Toast.makeText(main_activity.this, "请先更新数据", Toast.LENGTH_SHORT).show();
                }
            }
        });

        button2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                log.show();
            }
        });

        button3.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                log.show();
            }
        });

        buttonDB.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                buttonDB.setHint("已更新数据");
                int id001 = 0;
                pokemonlist pokeList001 = new pokemonlist();
                pokeList001.id = 1;
                pokeList001.number = "001";
                pokeList001.pixelphoto = "001";
                pokeList001.photo = "001";
                pokeList001.chname = "妙蛙种子";
                pokeList001.jpname = "フシギダネ";
                pokeList001.enname = "Bulbasaur";
                pokeList001.attribute1 = "grass";
                pokeList001.attribute2 = "poison";
                pokeList001.introduce = "妙蛙种子经常在阳光下酣睡。它背上有个种子，通过吸取阳光渐渐长大。";
                pokeList001.classes = "种子宝可梦";
                pokeList001.characteristic1 = "茂盛";
                pokeList001.characteristic2 = "叶绿素";
                pokeList001.height = "0.7m";
                pokeList001.weight = "6.9kg";
                pokeList001.egg1 = "怪兽";
                pokeList001.egg2 = "植物";
                pokeList001.probability = "45";
                pokeList001.steps = "5355";
                pokeList001.hp = "45";
                pokeList001.hpshow = "45dp";
                pokeList001.wg = "49";
                pokeList001.wgshow = "49dp";
                pokeList001.wf = "49";
                pokeList001.wfshow = "49dp";
                pokeList001.tg = "65";
                pokeList001.tgshow = "65dp";
                pokeList001.tf = "65";
                pokeList001.tfshow = "65dp";
                pokeList001.sd = "45";
                pokeList001.sdshow = "45dp";
                id001 = pokeDB.insert(pokeList001);
                int id002 = 0;
                pokemonlist pokeList002 = new pokemonlist();
                pokeList002.id = 2;
                pokeList002.number = "002";
                pokeList002.pixelphoto = "002";
                pokeList002.photo = "002";
                pokeList002.chname = "妙蛙草";
                pokeList002.jpname = "フシギソウ";
                pokeList002.enname = "Ivysaur";
                pokeList002.attribute1 = "grass";
                pokeList002.attribute2 = "poison";
                pokeList002.introduce = "在它的背上有一个花苞。妙蛙草的四肢非常粗壮，这样才能支撑它的体重。如果它开始经常晒太阳，表明它将要开花了。";
                pokeList002.classes = "种子宝可梦";
                pokeList002.characteristic1 = "茂盛";
                pokeList002.characteristic2 = "叶绿素";
                pokeList002.height = "1.0m";
                pokeList002.weight = "13.0kg";
                pokeList002.egg1 = "怪兽";
                pokeList002.egg2 = "植物";
                pokeList002.probability = "45";
                pokeList002.steps = "5355";
                pokeList002.hp = "60";
                pokeList002.hpshow = "60dp";
                pokeList002.wg = "62";
                pokeList002.wgshow = "62dp";
                pokeList002.wf = "63";
                pokeList002.wfshow = "63dp";
                pokeList002.tg = "80";
                pokeList002.tgshow = "80dp";
                pokeList002.tf = "80";
                pokeList002.tfshow = "80dp";
                pokeList002.sd = "60";
                pokeList002.sdshow = "60dp";
                id002 = pokeDB.insert(pokeList002);
                int id003 = 0;
                pokemonlist pokeList003 = new pokemonlist();
                pokeList003.id = 3;
                pokeList003.number = "003";
                pokeList003.pixelphoto = "003";
                pokeList003.photo = "003";
                pokeList003.chname = "妙蛙花";
                pokeList003.jpname = "フシギバナ";
                pokeList003.enname = "Venusaur";
                pokeList003.attribute1 = "grass";
                pokeList003.attribute2 = "poison";
                pokeList003.introduce = "妙蛙花的背上有一朵巨大的鲜花。如果它吸取养分、晒太阳，花的颜色就会变得非常鲜艳。花的香气还可以抚慰伤感的人。";
                pokeList003.classes = "种子宝可梦";
                pokeList003.characteristic1 = "茂盛";
                pokeList003.characteristic2 = "叶绿素";
                pokeList003.height = "2.0m";
                pokeList003.weight = "100.0kg";
                pokeList003.egg1 = "怪兽";
                pokeList003.egg2 = "植物";
                pokeList003.probability = "45";
                pokeList003.steps = "5355";
                pokeList003.hp = "80";
                pokeList003.hpshow = "80dp";
                pokeList003.wg = "82";
                pokeList003.wgshow = "82dp";
                pokeList003.wf = "83";
                pokeList003.wfshow = "83dp";
                pokeList003.tg = "100";
                pokeList003.tgshow = "100dp";
                pokeList003.tf = "100";
                pokeList003.tfshow = "100dp";
                pokeList003.sd = "80";
                pokeList003.sdshow = "80dp";
                id003 = pokeDB.insert(pokeList003);
                int id004 = 0;
                pokemonlist pokeList004 = new pokemonlist();
                pokeList004.id = 4;
                pokeList004.number = "004";
                pokeList004.pixelphoto = "004";
                pokeList004.photo = "004";
                pokeList004.chname = "小火龙";
                pokeList004.jpname = "ヒトカゲ";
                pokeList004.enname = "Charmander";
                pokeList004.attribute1 = "fire";
                pokeList004.attribute2 = "zero";
                pokeList004.introduce = "它尾巴上的火焰能够表现出它的情绪。当它开心时，火焰会摇曳。如果它被激怒，火焰就会猛烈地燃烧。";
                pokeList004.classes = "蜥蜴宝可梦";
                pokeList004.characteristic1 = "猛火";
                pokeList004.characteristic2 = "太阳之力";
                pokeList004.height = "0.6m";
                pokeList004.weight = "8.5kg";
                pokeList004.egg1 = "怪兽";
                pokeList004.egg2 = "龙";
                pokeList004.probability = "45";
                pokeList004.steps = "5355";
                pokeList004.hp = "39";
                pokeList004.hpshow = "39dp";
                pokeList004.wg = "52";
                pokeList004.wgshow = "52dp";
                pokeList004.wf = "43";
                pokeList004.wfshow = "43dp";
                pokeList004.tg = "60";
                pokeList004.tgshow = "60dp";
                pokeList004.tf = "50";
                pokeList004.tfshow = "50dp";
                pokeList004.sd = "65";
                pokeList004.sdshow = "65dp";
                id004 = pokeDB.insert(pokeList004);
                int id005 = 0;
                pokemonlist pokeList005 = new pokemonlist();
                pokeList005.id = 5;
                pokeList005.number = "005";
                pokeList005.pixelphoto = "005";
                pokeList005.photo = "005";
                pokeList005.chname = "火恐龙";
                pokeList005.jpname = "リザード";
                pokeList005.enname = "Charmeleon";
                pokeList005.attribute1 = "fire";
                pokeList005.attribute2 = "zero";
                pokeList005.introduce = "火恐龙会用它锋利的爪子残忍地撕裂敌人。如果它的敌人十分强壮，它就会变得好斗。在这种情况下，它尾巴上的火焰会变成带点蓝色的亮白。";
                pokeList005.classes = "火焰宝可梦";
                pokeList005.characteristic1 = "猛火";
                pokeList005.characteristic2 = "太阳之力";
                pokeList005.height = "1.1m";
                pokeList005.weight = "19.0kg";
                pokeList005.egg1 = "怪兽";
                pokeList005.egg2 = "龙";
                pokeList005.probability = "45";
                pokeList005.steps = "5355";
                pokeList005.hp = "58";
                pokeList005.hpshow = "58dp";
                pokeList005.wg = "64";
                pokeList005.wgshow = "64dp";
                pokeList005.wf = "58";
                pokeList005.wfshow = "58dp";
                pokeList005.tg = "80";
                pokeList005.tgshow = "80dp";
                pokeList005.tf = "65";
                pokeList005.tfshow = "65dp";
                pokeList005.sd = "80";
                pokeList005.sdshow = "80dp";
                id005 = pokeDB.insert(pokeList005);
                int id006 = 0;
                pokemonlist pokeList006 = new pokemonlist();
                pokeList006.id = 6;
                pokeList006.number = "006";
                pokeList006.pixelphoto = "006";
                pokeList006.photo = "006";
                pokeList006.chname = "喷火龙";
                pokeList006.jpname = "リザードン";
                pokeList006.enname = "Charizard";
                pokeList006.attribute1 = "fire";
                pokeList006.attribute2 = "flying";
                pokeList006.introduce = "喷火龙在空中飞行，寻找强大的对手。它吐出的火焰温度极高，可以融化一切物体。然而，它从来不攻击任何比它弱小的对手。";
                pokeList006.classes = "火焰宝可梦";
                pokeList006.characteristic1 = "猛火";
                pokeList006.characteristic2 = "太阳之力";
                pokeList006.height = "1.7m";
                pokeList006.weight = "90.5kg";
                pokeList006.egg1 = "怪兽";
                pokeList006.egg2 = "龙";
                pokeList006.probability = "45";
                pokeList006.steps = "5355";
                pokeList006.hp = "78";
                pokeList006.hpshow = "78dp";
                pokeList006.wg = "84";
                pokeList006.wgshow = "84dp";
                pokeList006.wf = "78";
                pokeList006.wfshow = "78dp";
                pokeList006.tg = "109";
                pokeList006.tgshow = "109dp";
                pokeList006.tf = "85";
                pokeList006.tfshow = "85dp";
                pokeList006.sd = "100";
                pokeList006.sdshow = "100dp";
                id006 = pokeDB.insert(pokeList006);
                int id007 = 0;
                pokemonlist pokeList007 = new pokemonlist();
                pokeList007.id = 7;
                pokeList007.number = "007";
                pokeList007.pixelphoto = "007";
                pokeList007.photo = "007";
                pokeList007.chname = "杰尼龟";
                pokeList007.jpname = "ゼニガメ";
                pokeList007.enname = "Squirtle";
                pokeList007.attribute1 = "water";
                pokeList007.attribute2 = "zero";
                pokeList007.introduce = "杰尼龟的壳不仅仅用来保护自己。它圆形的壳和表明的沟壑减小了它在水中的阻力，让这只神奇宝贝能高速游泳。";
                pokeList007.classes = "小龟宝可梦";
                pokeList007.characteristic1 = "激流";
                pokeList007.characteristic2 = "雨盘";
                pokeList007.height = "0.5m";
                pokeList007.weight = "9.0kg";
                pokeList007.egg1 = "怪兽";
                pokeList007.egg2 = "水中1";
                pokeList007.probability = "45";
                pokeList007.steps = "5355";
                pokeList007.hp = "44";
                pokeList007.hpshow = "44dp";
                pokeList007.wg = "48";
                pokeList007.wgshow = "48dp";
                pokeList007.wf = "65";
                pokeList007.wfshow = "65dp";
                pokeList007.tg = "50";
                pokeList007.tgshow = "50dp";
                pokeList007.tf = "64";
                pokeList007.tfshow = "64dp";
                pokeList007.sd = "43";
                pokeList007.sdshow = "43dp";
                id007 = pokeDB.insert(pokeList007);
                int id008 = 0;
                pokemonlist pokeList008 = new pokemonlist();
                pokeList008.id = 8;
                pokeList008.number = "008";
                pokeList008.pixelphoto = "008";
                pokeList008.photo = "008";
                pokeList008.chname = "卡咪龟";
                pokeList008.jpname = "カメール";
                pokeList008.enname = "Wartortle";
                pokeList008.attribute1 = "water";
                pokeList008.attribute2 = "zero";
                pokeList008.introduce = "蓬松的毛覆盖的大大的尾巴的颜色会随着年龄的增长而变深。背甲上的伤痕是强者的证明。";
                pokeList008.classes = "龟宝可梦";
                pokeList008.characteristic1 = "激流";
                pokeList008.characteristic2 = "雨盘";
                pokeList008.height = "1.0m";
                pokeList008.weight = "22.5kg";
                pokeList008.egg1 = "怪兽";
                pokeList008.egg2 = "水中1";
                pokeList008.probability = "45";
                pokeList008.steps = "5355";
                pokeList008.hp = "59";
                pokeList008.hpshow = "59dp";
                pokeList008.wg = "63";
                pokeList008.wgshow = "63dp";
                pokeList008.wf = "80";
                pokeList008.wfshow = "80dp";
                pokeList008.tg = "65";
                pokeList008.tgshow = "65dp";
                pokeList008.tf = "80";
                pokeList008.tfshow = "80dp";
                pokeList008.sd = "58";
                pokeList008.sdshow = "58dp";
                id008 = pokeDB.insert(pokeList008);
                int id009 = 0;
                pokemonlist pokeList009 = new pokemonlist();
                pokeList009.id = 9;
                pokeList009.number = "009";
                pokeList009.pixelphoto = "009";
                pokeList009.photo = "009";
                pokeList009.chname = "水箭龟";
                pokeList009.jpname = "カメックス";
                pokeList009.enname = "Blastoise";
                pokeList009.attribute1 = "water";
                pokeList009.attribute2 = "zero";
                pokeList009.introduce = "水箭龟背甲上伸出喷射口，可以精确瞄准，水弹可以击中50米外的空罐子。";
                pokeList009.classes = "甲壳宝可梦";
                pokeList009.characteristic1 = "激流";
                pokeList009.characteristic2 = "雨盘";
                pokeList009.height = "1.6m";
                pokeList009.weight = "85.5kg";
                pokeList009.egg1 = "怪兽";
                pokeList009.egg2 = "水中1";
                pokeList009.probability = "45";
                pokeList009.steps = "5355";
                pokeList009.hp = "79";
                pokeList009.hpshow = "79dp";
                pokeList009.wg = "83";
                pokeList009.wgshow = "83dp";
                pokeList009.wf = "100";
                pokeList009.wfshow = "100dp";
                pokeList009.tg = "85";
                pokeList009.tgshow = "85dp";
                pokeList009.tf = "105";
                pokeList009.tfshow = "105dp";
                pokeList009.sd = "78";
                pokeList009.sdshow = "78dp";
                id009 = pokeDB.insert(pokeList009);
                int id010 = 0;
                pokemonlist pokeList010 = new pokemonlist();
                pokeList010.id = 10;
                pokeList010.number = "010";
                pokeList010.pixelphoto = "010";
                pokeList010.photo = "010";
                pokeList010.chname = "绿毛虫";
                pokeList010.jpname = "キャタピー";
                pokeList010.enname = "Caterpie";
                pokeList010.attribute1 = "bug";
                pokeList010.attribute2 = "zero";
                pokeList010.introduce = "有着很好的食欲，可以瞬间吃掉比身体还大的叶子。触角会释放出强烈的臭味。";
                pokeList010.classes = "虫宝宝宝可梦";
                pokeList010.characteristic1 = "鳞粉";
                pokeList010.characteristic2 = "逃跑";
                pokeList010.height = "0.3m";
                pokeList010.weight = "2.9kg";
                pokeList010.egg1 = "昆虫";
                pokeList010.egg2 = "";
                pokeList010.probability = "255";
                pokeList010.steps = "4080";
                pokeList010.hp = "45";
                pokeList010.hpshow = "45dp";
                pokeList010.wg = "30";
                pokeList010.wgshow = "30dp";
                pokeList010.wf = "35";
                pokeList010.wfshow = "35dp";
                pokeList010.tg = "20";
                pokeList010.tgshow = "20dp";
                pokeList010.tf = "20";
                pokeList010.tfshow = "20dp";
                pokeList010.sd = "45";
                pokeList010.sdshow = "45dp";
                id010 = pokeDB.insert(pokeList010);
                int id011 = 0;
                pokemonlist pokeList011 = new pokemonlist();
                pokeList011.id = 11;
                pokeList011.number = "011";
                pokeList011.pixelphoto = "011";
                pokeList011.photo = "011";
                pokeList011.chname = "铁甲蛹";
                pokeList011.jpname = "トランセル";
                pokeList011.enname = "Metapod";
                pokeList011.attribute1 = "bug";
                pokeList011.attribute2 = "zero";
                pokeList011.introduce = "身体外面的壳有铁板那么硬。不怎么移动是因为里面柔软的身体正在准备进化。";
                pokeList011.classes = "蛹宝可梦";
                pokeList011.characteristic1 = "蜕皮";
                pokeList011.characteristic2 = "";
                pokeList011.height = "0.7m";
                pokeList011.weight = "9.9kg";
                pokeList011.egg1 = "昆虫";
                pokeList011.egg2 = "";
                pokeList011.probability = "120";
                pokeList011.steps = "4080";
                pokeList011.hp = "50";
                pokeList011.hpshow = "50dp";
                pokeList011.wg = "20";
                pokeList011.wgshow = "20dp";
                pokeList011.wf = "55";
                pokeList011.wfshow = "55dp";
                pokeList011.tg = "25";
                pokeList011.tgshow = "25dp";
                pokeList011.tf = "25";
                pokeList011.tfshow = "24dp";
                pokeList011.sd = "30";
                pokeList011.sdshow = "30dp";
                id011 = pokeDB.insert(pokeList011);
                int id012 = 0;
                pokemonlist pokeList012 = new pokemonlist();
                pokeList012.id = 12;
                pokeList012.number = "012";
                pokeList012.pixelphoto = "012";
                pokeList012.photo = "012";
                pokeList012.chname = "巴大蝶";
                pokeList012.jpname = "バタフリー";
                pokeList012.enname = "Butterfree";
                pokeList012.attribute1 = "bug";
                pokeList012.attribute2 = "flying";
                pokeList012.introduce = "寻找美味花蜜的能力非常好，离家10公里外开花的花蜜也可以找到并运回来。";
                pokeList012.classes = "蝴蝶宝可梦";
                pokeList012.characteristic1 = "复眼";
                pokeList012.characteristic2 = "有色眼镜";
                pokeList012.height = "1.1m";
                pokeList012.weight = "32.0kg";
                pokeList012.egg1 = "昆虫";
                pokeList012.egg2 = "";
                pokeList012.probability = "45";
                pokeList012.steps = "4080";
                pokeList012.hp = "60";
                pokeList012.hpshow = "60dp";
                pokeList012.wg = "45";
                pokeList012.wgshow = "45dp";
                pokeList012.wf = "50";
                pokeList012.wfshow = "50dp";
                pokeList012.tg = "90";
                pokeList012.tgshow = "90dp";
                pokeList012.tf = "80";
                pokeList012.tfshow = "80dp";
                pokeList012.sd = "70";
                pokeList012.sdshow = "70dp";
                id012 = pokeDB.insert(pokeList012);
                int id013 = 0;
                pokemonlist pokeList013 = new pokemonlist();
                pokeList013.id = 13;
                pokeList013.number = "013";
                pokeList013.pixelphoto = "013";
                pokeList013.photo = "013";
                pokeList013.chname = "独角虫";
                pokeList013.jpname = "ビードル";
                pokeList013.enname = "Weedle";
                pokeList013.attribute1 = "bug";
                pokeList013.attribute2 = "poison";
                pokeList013.introduce = "嗅觉非常灵敏，可以用大大的红鼻子从讨厌的叶子中嗅出自己喜欢的叶子的味道。";
                pokeList013.classes = "毛毛虫宝可梦";
                pokeList013.characteristic1 = "鳞粉";
                pokeList013.characteristic2 = "逃跑";
                pokeList013.height = "0.3m";
                pokeList013.weight = "3.2kg";
                pokeList013.egg1 = "昆虫";
                pokeList013.egg2 = "";
                pokeList013.probability = "255";
                pokeList013.steps = "4080";
                pokeList013.hp = "40";
                pokeList013.hpshow = "40dp";
                pokeList013.wg = "35";
                pokeList013.wgshow = "35dp";
                pokeList013.wf = "30";
                pokeList013.wfshow = "30dp";
                pokeList013.tg = "20";
                pokeList013.tgshow = "20dp";
                pokeList013.tf = "20";
                pokeList013.tfshow = "20dp";
                pokeList013.sd = "50";
                pokeList013.sdshow = "50dp";
                id013 = pokeDB.insert(pokeList013);
                int id014 = 0;
                pokemonlist pokeList014 = new pokemonlist();
                pokeList014.id = 14;
                pokeList014.number = "014";
                pokeList014.pixelphoto = "014";
                pokeList014.photo = "014";
                pokeList014.chname = "铁壳蛹";
                pokeList014.jpname = "コクーン";
                pokeList014.enname = "Kakuna";
                pokeList014.attribute1 = "bug";
                pokeList014.attribute2 = "poison";
                pokeList014.introduce = "挂在树上几乎一动不动是为了进化忙碌地准备着，证据是身体在逐渐变热。";
                pokeList014.classes = "蛹宝可梦";
                pokeList014.characteristic1 = "蜕皮";
                pokeList014.characteristic2 = "";
                pokeList014.height = "0.6m";
                pokeList014.weight = "10.0kg";
                pokeList014.egg1 = "昆虫";
                pokeList014.egg2 = "";
                pokeList014.probability = "120";
                pokeList014.steps = "4080";
                pokeList014.hp = "45";
                pokeList014.hpshow = "45dp";
                pokeList014.wg = "25";
                pokeList014.wgshow = "25dp";
                pokeList014.wf = "50";
                pokeList014.wfshow = "50dp";
                pokeList014.tg = "25";
                pokeList014.tgshow = "25dp";
                pokeList014.tf = "25";
                pokeList014.tfshow = "25dp";
                pokeList014.sd = "35";
                pokeList014.sdshow = "35dp";
                id014 = pokeDB.insert(pokeList014);
                int id015 = 0;
                pokemonlist pokeList015 = new pokemonlist();
                pokeList015.id = 15;
                pokeList015.number = "015";
                pokeList015.pixelphoto = "015";
                pokeList015.photo = "015";
                pokeList015.chname = "大针蜂";
                pokeList015.jpname = "スピアー";
                pokeList015.enname = "Beedrill";
                pokeList015.attribute1 = "bug";
                pokeList015.attribute2 = "poison";
                pokeList015.introduce = "保护领地的意识非常强，为了安全不会让任何人接近自己的巢穴，生气的话就会一起攻上来。";
                pokeList015.classes = "毒蜂宝可梦";
                pokeList015.characteristic1 = "虫之预感";
                pokeList015.characteristic2 = "狙击手";
                pokeList015.height = "1.0m";
                pokeList015.weight = "29.5kg";
                pokeList015.egg1 = "昆虫";
                pokeList015.egg2 = "";
                pokeList015.probability = "45";
                pokeList015.steps = "4080";
                pokeList015.hp = "65";
                pokeList015.hpshow = "65dp";
                pokeList015.wg = "90";
                pokeList015.wgshow = "90dp";
                pokeList015.wf = "40";
                pokeList015.wfshow = "40dp";
                pokeList015.tg = "45";
                pokeList015.tgshow = "45dp";
                pokeList015.tf = "80";
                pokeList015.tfshow = "80dp";
                pokeList015.sd = "75";
                pokeList015.sdshow = "75dp";
                id015 = pokeDB.insert(pokeList015);
                int id016 = 0;
                pokemonlist pokeList016 = new pokemonlist();
                pokeList016.id = 16;
                pokeList016.number = "016";
                pokeList016.pixelphoto = "016";
                pokeList016.photo = "016";
                pokeList016.chname = "波波";
                pokeList016.jpname = "ポッポ";
                pokeList016.enname = "Pidgey";
                pokeList016.attribute1 = "normal";
                pokeList016.attribute2 = "flying";
                pokeList016.introduce = "方向感非常好，无论在多远的地方迷路了都能回到自己的巢穴。";
                pokeList016.classes = "小鸟宝可梦";
                pokeList016.characteristic1 = "锐利目光";
                pokeList016.characteristic2 = "健壮胸肌";
                pokeList016.height = "0.3m";
                pokeList016.weight = "1.8kg";
                pokeList016.egg1 = "飞行";
                pokeList016.egg2 = "";
                pokeList016.probability = "255";
                pokeList016.steps = "4080";
                pokeList016.hp = "40";
                pokeList016.hpshow = "40dp";
                pokeList016.wg = "45";
                pokeList016.wgshow = "45dp";
                pokeList016.wf = "40";
                pokeList016.wfshow = "40dp";
                pokeList016.tg = "35";
                pokeList016.tgshow = "35dp";
                pokeList016.tf = "35";
                pokeList016.tfshow = "35dp";
                pokeList016.sd = "56";
                pokeList016.sdshow = "56dp";
                id016 = pokeDB.insert(pokeList016);
                int id017 = 0;
                pokemonlist pokeList017 = new pokemonlist();
                pokeList017.id = 17;
                pokeList017.number = "017";
                pokeList017.pixelphoto = "017";
                pokeList017.photo = "017";
                pokeList017.chname = "比比鸟";
                pokeList017.jpname = "ピジョン";
                pokeList017.enname = "Pidgeotto";
                pokeList017.attribute1 = "normal";
                pokeList017.attribute2 = "flying";
                pokeList017.introduce = "在广大的领土范围里飞翔巡视，如果领地被侵犯，会用锐利的爪子毫不留情地惩治对方。";
                pokeList017.classes = "鸟宝可梦";
                pokeList017.characteristic1 = "锐利目光";
                pokeList017.characteristic2 = "健壮胸肌";
                pokeList017.height = "1.1m";
                pokeList017.weight = "30.0kg";
                pokeList017.egg1 = "飞行";
                pokeList017.egg2 = "";
                pokeList017.probability = "120";
                pokeList017.steps = "4080";
                pokeList017.hp = "63";
                pokeList017.hpshow = "63dp";
                pokeList017.wg = "60";
                pokeList017.wgshow = "60dp";
                pokeList017.wf = "55";
                pokeList017.wfshow = "55dp";
                pokeList017.tg = "50";
                pokeList017.tgshow = "50dp";
                pokeList017.tf = "50";
                pokeList017.tfshow = "50dp";
                pokeList017.sd = "71";
                pokeList017.sdshow = "71dp";
                id017 = pokeDB.insert(pokeList017);
                int id018 = 0;
                pokemonlist pokeList018 = new pokemonlist();
                pokeList018.id = 18;
                pokeList018.number = "018";
                pokeList018.pixelphoto = "018";
                pokeList018.photo = "018";
                pokeList018.chname = "大比鸟";
                pokeList018.jpname = "ピジョット";
                pokeList018.enname = "Pidgeot";
                pokeList018.attribute1 = "normal";
                pokeList018.attribute2 = "flying";
                pokeList018.introduce = "翅膀的光泽非常漂亮，很多训练家被它头顶羽毛的美丽所吸引而培育它。";
                pokeList018.classes = "鸟宝可梦";
                pokeList018.characteristic1 = "锐利目光";
                pokeList018.characteristic2 = "健壮胸肌";
                pokeList018.height = "1.5m";
                pokeList018.weight = "39.5kg";
                pokeList018.egg1 = "飞行";
                pokeList018.egg2 = "";
                pokeList018.probability = "45";
                pokeList018.steps = "4080";
                pokeList018.hp = "83";
                pokeList018.hpshow = "83dp";
                pokeList018.wg = "80";
                pokeList018.wgshow = "80dp";
                pokeList018.wf = "75";
                pokeList018.wfshow = "75dp";
                pokeList018.tg = "70";
                pokeList018.tgshow = "70dp";
                pokeList018.tf = "70";
                pokeList018.tfshow = "70dp";
                pokeList018.sd = "101";
                pokeList018.sdshow = "101dp";
                id018 = pokeDB.insert(pokeList018);
                int id019 = 0;
                pokemonlist pokeList019 = new pokemonlist();
                pokeList019.id = 19;
                pokeList019.number = "019";
                pokeList019.pixelphoto = "019";
                pokeList019.photo = "019";
                pokeList019.chname = "小拉达";
                pokeList019.jpname = "コラッタ";
                pokeList019.enname = "Rattata";
                pokeList019.attribute1 = "normal";
                pokeList019.attribute2 = "zero";
                pokeList019.introduce = "警戒心很强，就算睡着的时候耳朵也会聆听着周围的动静。无论在什么地方都可以筑巢。";
                pokeList019.classes = "鼠宝可梦";
                pokeList019.characteristic1 = "毅力";
                pokeList019.characteristic2 = "活力";
                pokeList019.height = "0.3m";
                pokeList019.weight = "3.5kg";
                pokeList019.egg1 = "陆上";
                pokeList019.egg2 = "";
                pokeList019.probability = "255";
                pokeList019.steps = "4080";
                pokeList019.hp = "30";
                pokeList019.hpshow = "30dp";
                pokeList019.wg = "56";
                pokeList019.wgshow = "56dp";
                pokeList019.wf = "35";
                pokeList019.wfshow = "35dp";
                pokeList019.tg = "25";
                pokeList019.tgshow = "25dp";
                pokeList019.tf = "35";
                pokeList019.tfshow = "35dp";
                pokeList019.sd = "72";
                pokeList019.sdshow = "72dp";
                id019 = pokeDB.insert(pokeList019);
                int id020 = 0;
                pokemonlist pokeList020 = new pokemonlist();
                pokeList020.id = 20;
                pokeList020.number = "020";
                pokeList020.pixelphoto = "020";
                pokeList020.photo = "020";
                pokeList020.chname = "拉达";
                pokeList020.jpname = "ラッタ";
                pokeList020.enname = "Raticate";
                pokeList020.attribute1 = "normal";
                pokeList020.attribute2 = "zero";
                pokeList020.introduce = "坚固的门牙不断伸长，要通过啮咬岩石或者大树来削短。也有可能啃食人家的墙壁。";
                pokeList020.classes = "鼠宝可梦";
                pokeList020.characteristic1 = "毅力";
                pokeList020.characteristic2 = "活力";
                pokeList020.height = "0.7m";
                pokeList020.weight = "18.5kg";
                pokeList020.egg1 = "陆上";
                pokeList020.egg2 = "";
                pokeList020.probability = "127";
                pokeList020.steps = "4080";
                pokeList020.hp = "55";
                pokeList020.hpshow = "55dp";
                pokeList020.wg = "81";
                pokeList020.wgshow = "81dp";
                pokeList020.wf = "60";
                pokeList020.wfshow = "60dp";
                pokeList020.tg = "50";
                pokeList020.tgshow = "50dp";
                pokeList020.tf = "70";
                pokeList020.tfshow = "70dp";
                pokeList020.sd = "97";
                pokeList020.sdshow = "97dp";
                id020 = pokeDB.insert(pokeList020);
            }
        });
    }

}
